#version 440

layout(local_size_x_id = 0, local_size_y_id = 1) in; // workgroup dimensions specialization constants
layout(push_constant) uniform Parameters {
   uint width;
   uint height;
} p;
layout(std430, binding = 0) buffer buf0 { float I[]; };

void main() {
   uint x = gl_GlobalInvocationID.x;
   uint y = gl_GlobalInvocationID.y;
   if  (p.width <= x || p.height <= y) return;

   I[p.width*y + x] = 0.f;

}
