// shader to test running kernels with empty push constants interface
#version 440

layout(local_size_x_id = 0) in; // workgroup size set with specialization constant
struct Parameters{
   uint size; // array size
   float a;   // scaling parameter
};

layout(std430, binding = 0) buffer lay0 { float arr_y[]; }; // array parameters
layout(std430, binding = 1) buffer lay1 { float arr_x[]; };

void main(){
   Parameters params = Parameters(128, 0.1f);
   const uint id = gl_GlobalInvocationID.x; // current offset
   if(params.size <= id){                   // drop threads outside the buffer
      return;
   }
   arr_y[id] += params.a*arr_x[id];         // saxpy
}
